stages:
  dataset_creation:
    cmd: python scripts/create_dataset.py
    deps:
    - scripts/create_dataset.py
    outs:
    - assets/data
  features_creation:
    cmd: python scripts/extract_features.py
    deps:
    - assets/data
    - scripts/extract_features.py
    outs:
    - assets/features
